In [1]:
import pickle
import argparse
from utils.cell_lifting import graph_to_edge_index, get_rings
from toponetx.classes.cell_complex import CellComplex
import time
import numpy as np

In [3]:
with open(f'data/qm9_train_nx.pkl', 'rb') as f:
    qm9_train = pickle.load(f)
    
with open(f'data/qm9_test_nx.pkl', 'rb') as f:
    test_mols = pickle.load(f)
    
# # extract ring from each molecular graph 
# mol_train_rings = []
# mol_test_rings = []

# qm9_train_cell_complex = []
# qm9_test_cell_complex = []

# for graph in qm9_train:
#     attribute = {'gap': graph.graph['gap'], 'U0': graph.graph['U0']}
#     edge_index = graph_to_edge_index(graph)
#     if edge_index.nelement() == 0:
#         mol_test_rings.append([])
#         continue
#     rings = get_rings(edge_index)
#     # turn each molecular graph into a cell complex 
#     cell_complex = CellComplex(graph, attribute)
#     cell_complex.add_cells_from(rings, rank = 2)
    
#     mol_train_rings.append(rings)
#     qm9_train_cell_complex.append(cell_complex)
    
# for graph in test_mols:
#     attribute = {'gap': graph.graph['gap'], 'U0': graph.graph['U0']}
#     edge_index = graph_to_edge_index(graph)
#     if edge_index.nelement() == 0:
#         mol_test_rings.append([])
#         continue
#     rings = get_rings(edge_index)
#     cell_complex = CellComplex(graph, attribute)
#     cell_complex.add_cells_from(rings, rank = 2)
    
#     mol_test_rings.append(rings)
#     qm9_test_cell_complex.append(cell_complex)
    
# with open(f'data/qm9_train_cell_complex.pkl', 'wb') as f:
#     pickle.dump(qm9_train_cell_complex, f)
# with open(f'data/qm9_test_cell_complex.pkl', 'wb') as f:
#     pickle.dump(qm9_test_cell_complex, f)

TypeError: No registered converter was able to produce a C++ rvalue of type std::string from this Python object of type str

In [8]:
from rdkit import Chem

TypeError: No registered converter was able to produce a C++ rvalue of type std::string from this Python object of type str

In [ ]:
with open(f'data/qm9_test_cell_complex.pkl', 'rb') as f:
    qm9_test_cell_complex = pickle.load(f)
    
cell_complex = qm9_test_cell_complex[0]   

In [ ]:
# value we want to predict
print(cell_complex.name)

# node attributes
print('example of node attributes')
print(cell_complex.get_node_attributes('label'))
print(cell_complex.get_node_attributes('atomic_num'))
# edge attributes
print('edge attributes')
print(cell_complex.get_edge_attributes('label'))
print()


{'gap': 0.3028, 'U0': -401.011905}
example of node attributes
{0: 'C', 1: 'C', 2: 'O', 3: 'C', 4: 'O', 5: 'C', 6: 'C', 7: 'N'}
{0: 6, 1: 6, 2: 8, 3: 6, 4: 8, 5: 6, 6: 6, 7: 7}
edge attributes
{(0, 1): 1, (1, 2): 1, (1, 3): 1, (3, 4): 1, (3, 5): 1, (5, 6): 1, (6, 7): 3}


CellView([])

In [ ]:
import torch
print('adjacency matrix')
a = cell_complex.adjacency_matrix(rank=0).todense()
print(a)
print('lower adjacency matrix of bonds')
print(cell_complex.down_laplacian_matrix(rank=1).todense())
print('upper adjacency matrix of bonds')

lower_neighborhood_t = cell_complex.down_laplacian_matrix(rank=1)

try:
    upper_neighborhood_t = cell_complex.up_laplacian_matrix(rank=1).todense()
except:
    upper_neighborhood_t = np.zeros(
        (lower_neighborhood_t.shape[0], lower_neighborhood_t.shape[0])
    )
    upper_neighborhood_t = torch.from_numpy(upper_neighborhood_t)
print(upper_neighborhood_t)

adjacency matrix
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]]
lower adjacency matrix of bonds
[[ 2. -1. -1.  0.  0.  0.  0.]
 [-1.  2.  1.  0.  0.  0.  0.]
 [-1.  1.  2. -1. -1.  0.  0.]
 [ 0.  0. -1.  2.  1.  0.  0.]
 [ 0.  0. -1.  1.  2. -1.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0. -1.  2.]]
upper adjacency matrix of bonds
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]], dtype=torch.float64)
